First version of the feature send icons
TheNitek/draw pull request #1
Opened 2021-12-30 00:32 UTC by el-paso

2021-12-30 00:32 UTC, el-paso commented
With this feature you can send 8x8 icons to the LED matrix.

2021-12-30 05:29 UTC, el-paso commented
Please review and merge @TheNitek

2022-01-02 17:10 UTC, TheNitek commented
What's the license of the png files?

2022-01-04 10:26 UTC, TheNitek requested changes

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +      .tg  {
tg?

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +      .tg th {
Are there any THs?

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +      img {
Should probably be a class

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +            const element = d[i];
Never used?

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +            client.send(message);
No need to send this pixel by pixel. The matrix can be updated using one 128byte message

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +    <center>
Deprecated

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +    <br>
Why interrupt the <script> with pieces of HTML? Putting the HTML with the rest is probably more readable

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +    cell.innerHTML = "<picture><img src=\""+icons[i].iconPath+"\" alt=\""+icons[i].iconTitle+"\" style=\"width:64px;height:64px;\" onclick=\"sendIcon('"+icons[i].iconPath+"')\"></picture>";
move style into class from line 86?

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +    <canvas id="myCanvas" width="8" height="8" style="border:1px solid #ff0000; display: none;">
myCanvas seems a bit generic

why have a border with display: none?

2022-01-04 10:26 UTC, TheNitek commented on web/index.html
> +    cell.innerHTML = "<picture><img src=\""+icons[i].iconPath+"\" alt=\""+icons[i].iconTitle+"\" style=\"width:64px;height:64px;\" onclick=\"sendIcon('"+icons[i].iconPath+"')\"></picture>";
Probably no need for <picture> tag?

2022-01-04 15:52 UTC, el-paso commented on web/index.html
> +    <canvas id="myCanvas" width="8" height="8" style="border:1px solid #ff0000; display: none;">
Changed it to ```iconPlaceholder```

2022-01-04 15:53 UTC, el-paso commented on web/index.html
> +    cell.innerHTML = "<picture><img src=\""+icons[i].iconPath+"\" alt=\""+icons[i].iconTitle+"\" style=\"width:64px;height:64px;\" onclick=\"sendIcon('"+icons[i].iconPath+"')\"></picture>";
Done

2022-01-04 15:53 UTC, el-paso commented on web/index.html
> +    <br>
Changed it

2022-01-04 15:54 UTC, el-paso commented on web/index.html
> +            client.send(message);
@TheNitek how does the message has to be formatted?

2022-01-04 15:54 UTC, el-paso commented on web/index.html
> +      img {
Done

2022-01-04 15:55 UTC, el-paso commented on web/index.html
> +            const element = d[i];
Deleted the line

2022-01-04 17:41 UTC, TheNitek commented on web/index.html
> +            client.send(message);
https://github.com/TheNitek/draw/blob/f4ccb2c3e06d3de02b21f85f4c60568ee3ac5640/web/index.html#L123

2022-01-07 14:26 UTC, el-paso commented on web/index.html
> +      .tg  {
renamed it to iconTable

2022-01-07 14:26 UTC, el-paso commented on web/index.html
> +      .tg th {
deleted.

2022-01-07 14:26 UTC, el-paso commented on web/index.html
> +    <center>
Done

2022-01-07 14:27 UTC, el-paso commented on web/index.html
> +    cell.innerHTML = "<picture><img src=\""+icons[i].iconPath+"\" alt=\""+icons[i].iconTitle+"\" style=\"width:64px;height:64px;\" onclick=\"sendIcon('"+icons[i].iconPath+"')\"></picture>";
Done

2022-01-07 15:04 UTC, el-paso commented
> What's the license of the png files?

I have changed the pictures to versions with  CC0 license.

2022-01-07 16:14 UTC, el-paso commented on web/index.html
> +            client.send(message);
Done

2022-01-07 16:16 UTC, el-paso commented
@TheNitek . All requested changes are implemented. Please review and merge.

2022-01-11 19:03 UTC, merged